### ISSUE TITLE
Fix `yarn test:unit`

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#724]
Running `yarn test:unit` gives error

```
 yarn test
yarn run v1.22.4
$ jest App
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
 FAIL  App/stores/api.test.ts
  ● Test suite failed to run

    SyntaxError: /Users/amaury/Workspace/shootismoke/shoot-i-smoke/node_modules/react-native/Libraries/polyfills/error-guard.js: Unexpected token, expected ";" (14:5)

      12 | let _inGuard = 0;
      13 | 
    > 14 | type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         |      ^
      15 | type Fn<Args, Return> = (...Args) => Return;
      16 | 
      17 | /**

      at Parser._raise (node_modules/@babel/parser/lib/index.js:742:17)
      at Parser.raiseWithData (node_modules/@babel/parser/lib/index.js:735:17)
      at Parser.raise (node_modules/@babel/parser/lib/index.js:729:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:8757:16)
      at Parser.semicolon (node_modules/@babel/parser/lib/index.js:8739:40)
      at Parser.parseExpressionStatement (node_modules/@babel/parser/lib/index.js:11614:10)
      at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:11215:19)
      at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:11081:17)
      at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:11656:25)
      at Parser.parseBlockBody (node_modules/@babel/parser/lib/index.js:11642:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.651s
Ran all test suites matching /App/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amaurymartiny** [comment]
fixed in #753
